#! /bin/bash

# Pre-installation script for bng_0.1_all.deb. Removes the old version of bng

echo "Looking for old versions of bng..."
if [ -f "$HOME/bin/bng" ]; then
    echo "Old version found. Removing..."
    sudo rm -f /usr/bin/bng
    echo "Old version removed."
fi

if [ -f "usr/local/bin/bng" ]; then 
    echo "Old version found. Removing..."
    sudo rm -f /usr/local/bin/bng
    echo "Old version removed."
fi

if [ -f "/usr/bin/bng" ]; then
    echo "Old version found. Removing..."
    sudo rm -f /usr/bin/bng
    echo "Old version removed."
fi

if [ -f "/usr/share/applications/bng.desktop" ]; then
    echo "Old version found. Removing..."
    sudo rm -f /usr/share/applications/bng.desktop
    echo "Old version removed."
fi

if [ -f "/usr/share/icons/bng.png" ]; then
    echo "Old version found. Removing..."
    sudo rm -f /usr/share/icons/bng.png
    echo "Old version removed."
fi
